# -*- coding: utf-8 -*-
"""Explorando_IA_Generativa_Pipeline_ETL_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvLNCqPHYihwQjKENFIyzjldmB7PtleS

# Etapa de Load
Carregar dados do arquivo Pipeline_ETL_Python.csv para análise e tratativa dos dados.
"""

import pandas as pd

def read_csv_robust(filepath, encoding='latin1'):
    with open(filepath, 'r', encoding=encoding) as f:
        lines = f.readlines()

    # Extract header from the first line, stripping quotes
    header = [h.strip().strip('"') for h in lines[0].strip().split(',')]

    # Process data lines, stripping quotes
    data = []
    for line in lines[1:]:
        if line.strip(): # Avoid processing empty lines
            data.append([d.strip().strip('"') for d in line.strip().split(',')])

    return pd.DataFrame(data, columns=header)

# Lê o CSV usando a função robusta e converte para uma lista de dicionários
df_users = read_csv_robust('Pipeline_ETL_Python.csv', encoding='latin1')
users = df_users.to_dict(orient='records')

# Garante a estrutura esperada para a etapa de Transformação
for user in users:
    # Initialize 'news' as an empty list, and ensure 'id' is an integer
    user['news'] = []
    if 'UserID' in user: # Using 'UserID' as per CSV, convert to 'id' if needed later for API
        user['id'] = int(user.pop('UserID')) # Convert and rename for consistency with API structure

"""## **E**xtract

Extraia a lista de IDs de usuário a partir do arquivo CSV. Para cada ID, faça uma requisição GET para obter os dados do usuário correspondente.

### ⬆️ Faça o upload do arquivo `Pipeline_ETL_Python.csv`

**O arquivo já está carregado no caminho `/Pipeline_ETL_Python.csv`.** A instrução abaixo era para o caso de o arquivo não ter sido encontrado. Você pode prosseguir com a execução das células.
"""

import pandas as pd

# Helper function to robustly read CSV, assuming it's defined once globally or locally for safety
def read_csv_robust(filepath, encoding='latin1'):
    with open(filepath, 'r', encoding=encoding) as f:
        lines = f.readlines()

    header = [h.strip().strip('"') for h in lines[0].strip().split(',')]
    data = []
    for line in lines[1:]:
        if line.strip():
            data.append([d.strip().strip('"') for d in line.strip().split(',')])

    return pd.DataFrame(data, columns=header)

try:
    df_check = read_csv_robust('Pipeline_ETL_Python.csv', encoding='latin1')
    print("Primeiras linhas do CSV:")
    print(df_check.head())
    print("Nomes das colunas no CSV:")
    print(df_check.columns.tolist())
except FileNotFoundError:
    print("Erro: O arquivo 'Pipeline_ETL_Python.csv' não foi encontrado no diretório especificado. Por favor, verifique se o arquivo foi carregado corretamente.")
except Exception as e:
    print(f"Ocorreu um erro durante a leitura do CSV: {e}")

import pandas as pd

# Função auxiliar para leitura robusta de CSV
def read_csv_robust(filepath, encoding='latin1'):
    with open(filepath, 'r', encoding=encoding) as f:
        lines = f.readlines()

    header = [h.strip().strip('"') for h in lines[0].strip().split(',')]
    data = []
    for line in lines[1:]:
        if line.strip():
            data.append([d.strip().strip('"') for d in line.strip().split(',')])

    return pd.DataFrame(data, columns=header)

try:
    df = read_csv_robust('Pipeline_ETL_Python.csv', encoding='latin1')

    if 'UserID' not in df.columns:
        raise KeyError("A coluna 'UserID' não foi encontrada no arquivo CSV. Por favor, verifique o cabeçalho do arquivo.")

    # Verificar se o UserID seja do tipo inteiro
    user_ids = df['UserID'].astype(int).tolist()
    print(user_ids)
except FileNotFoundError:
    print("Erro: O arquivo 'Pipeline_ETL_Python.csv' não foi encontrado no diretório especificado (/Pipeline_ETL_Python.csv). Certifique-se de que o arquivo foi carregado.")
    user_ids = [] # Define uma lista vazia para evitar erros subsequentes
except KeyError as e:
    print(f"Erro na leitura do CSV: {e}")
    user_ids = [] # Define uma lista vazia para evitar erros subsequentes
except Exception as e:
    print(f"Ocorreu um erro inesperado durante o parsing do CSV: {e}")
    user_ids = []

import json

# A lista 'users' já foi populada a partir do arquivo CSV na célula anterior (FKqLC_CWoYqR).
# Esta célula agora simplesmente exibirá os dados dos usuários extraídos localmente.
print(json.dumps(users, indent=2))

"""## **T**ransform

Utilize a API do OpenAI GPT-4 para gerar uma mensagem de marketing personalizada para cada usuário.
"""

!pip install openai

# Documentação Oficial da API OpenAI: https://platform.openai.com/docs/api-reference/introduction
# Informações sobre o Período Gratuito: https://help.openai.com/en/articles/4936830

# Para gerar uma API Key:
# 1. Crie uma conta na OpenAI
# 2. Acesse a seção "API Keys"
# 3. Clique em "Create API Key"
# Link direto: https://platform.openai.com/account/api-keys

# Substitua o texto TODO por sua API Key da OpenAI, ela será salva como uma variável de ambiente.
openai_api_key = 'TODO'

import openai

# Initialize the OpenAI client with your API key
client = openai.OpenAI(api_key=openai_api_key)

def generate_ai_news(user):
  completion = client.chat.completions.create(
    model="gpt-4",
    messages=[
      {
          "role": "system",
          "content": "Você é um especialista em markting bancário."
      },
      {
          "role": "user",
          "content": f"Crie uma mensagem para {user['Name']} sobre a importância dos investimentos (máximo de 100 caracteres)"
      }
    ]
  )
  # Accessing the content from the new response object structure
  return completion.choices[0].message.content.strip('"')

# Process only the first 5 users
for i in range(min(5, len(users))):
    user = users[i]
    news = generate_ai_news(user)
    print(f"Mensagem para {user['Name']}: {news}")
    user['news'].append({
        "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
        "description": news
    })

"""## **L**oad

Atualize a lista de "news" de cada usuário na API com a nova mensagem gerada.
"""

import json

# Como a API está indisponível, a etapa de Load será substituída por exibir os dados atualizados no console.
# Conforme a célula de texto '## E a Etapa de Load?' (aVO2UazRGCwz) indica.

print("\n--- Usuários com mensagens atualizadas (Etapa de Load) ---")
print(json.dumps(users, indent=2))